### ISSUE TITLE
Dataset split (Train, val, test)

### ISSUE THREAD

**Issue by smistad** [echonet/lvh#13]
In your paper you state that the number of videos per dataset split were:
Train: 9601 
Val: 1200 
Test: 1200 
Total: 12001 

However in the MeasurementsLists.csv the file count per split is the following:
Train: 10189 
Val: 1145 
Test: 337 
Total: 11671

Can you please share the true split you used in the paper so we can compare more correctly with the results in your paper?

**Comment by Teddyred999** [comment]
Have u resolved this issue?  I'm still facing the same problem. - -

**Comment by echonet** [comment]
We apologize for the inconvenience, we have updated the repo with our old split as described in the paper. The file is hashed_index_old_split.csv
