### ISSUE TITLE
Dataset distribution

### ISSUE THREAD

**Issue by Teddyred999** [echonet/lvh#15]
I have encountered an issue while replicating a paper. 
In the paper, the dataset distribution is stated as follows: **train 9600, val 1200, test 1200**. 
However, in the dataset table, the split is shown as **train 10490, val 1167, test 343**. 

To ensure a fair comparison, how should I address this discrepancy? Additionally, there are some errors in the dataset's MeasurementsList.csv file. If the authors wish, I am willing to send the modified MeasurementsList.csv along with the computed **pixel spacing** to your email. Looking forward to your response.

**Comment by echonet** [comment]
Thanks for checking. On initial inspection, you are correct and it appears to spreadsheet has the incorrect split. We will check if we have the prior log files to confirm previous split.

**Comment by Teddyred999** [comment]
Thank you for your response. If there are any **updates** on the table information, I hope you could notify me! I am looking forward to conducting further research on model building based on this excellent work. Thank you once again for your time！

**Comment by echonet** [comment]
Please see updated CSV: hashed_index_old_split.csv
