### ISSUE TITLE
The dataset

### ISSUE THREAD

**Issue by NanYoMy** [echonet/lvh#3]
Hi, 
I have to download the dataset for echonet-lvh. 
However, the dataset linker is totally the same as the dataset in echonet-dynamic. 
Especially, measurements such as "LVS", "LVID", and "LVPW" were not provided.

**Comment by KimYeongHyeon** [comment]
Check on https://echonet.github.io/lvh/

**Comment by SamNaqvi2019** [comment]
Hi, 
I faced the same issue. The link shared above downloads Echonet-Dynamic containing 10031 videos only with no additional labels.

**Comment by echonet** [comment]
Please refresh and clear cache

**Comment by SamNaqvi2019** [comment]
Alright. Thank you.

**Comment by SamNaqvi2019** [comment]
Hello,

I am currently trying to work on your dataset; Echonet-LVH. Are the labels
for different diseases such as Cardiac Amyloidosis, Aortic Stenosis and HCM
(as mentioned in the relevant paper) available for hypertrophic disease
classification?

Regards,
Samana Batool

**Comment by staniPetrox** [comment]
No, see here:
https://github.com/echonet/lvh/issues/9
