### ISSUE TITLE
Physical unit

### ISSUE THREAD

**Issue by KimYeongHyeon** [echonet/lvh#4]
what is the physical unit for pixel?

according to your paper, i think 1mm per 1 pixel, right?

**Comment by smistad** [comment]
I have the same questions. 
How can we calculate the physical size of the videos?
This is necessary to get the measurements in physical units. The example script here seems to only calculate the measurements in pixels.
Without this it is not possible to reproduce your results.

**Comment by echonet** [comment]
Please see updated hashed_index_old_split.csv
