### ISSUE TITLE
Access to labels for LVH etiologies.

### ISSUE THREAD

**Issue by KianTigger** [echonet/lvh#6]
Hello I'm following up on a question Samana Batool asked on another thread, their question was as follows.

I am currently trying to work on your dataset; Echonet-LVH. Are the labels
for different diseases such as Cardiac Amyloidosis, Aortic Stenosis and HCM
(as mentioned in the relevant paper) available for hypertrophic disease
classification?

Is this something we will ever gain access to? 
Many thanks,
Kian Kordtomeikel

**Comment by douyang** [comment]
Unfortunately that is not available in this version of the data release.
