### ISSUE TITLE
LVH no labels

### ISSUE THREAD

**Issue by staniPetrox** [echonet/lvh#9]
As others have already mentioned, you did not publish the most important part of the paper: the labels for HCM and other heart conditions. In your paper you mentioned your intention to create a benchmark dataset, however you did not publish the most important part of your data, the true labels. What you do is contrary to what you said in your peer reviewed journal contribution. This is deceiving.

**Comment by douyang** [comment]
The public release dataset is for PLAX videos and wall thickness. The etiologies include for rare diseases, which can be potentially identifying given it’s rare nature.
